services:
  nats-server:
    image: nats
    ports:
      - 8222:8222
  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.dev
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVER=nats://nats-server:4222
  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.dev
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVER=nats://nats-server:4222
      - DATABASE_URL=${AUTH_MS_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.dev
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVER=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db
  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.dev
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVER=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_MS_DATABASE_URL_DEV}
    depends_on:
      - orders-db
  orders-db:
    image: postgres:16.2
    restart: always
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    ports:
      - 5430:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders
  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: dockerfile.dev
    ports:
      - 3003:3000
    volumes:
      - ./payments-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVER=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
