services:
  nats-server:
    image: nats
  client-gateway:
    build: ./client-gateway
    image: client-gateway-prd
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    environment:
      - PORT=3000
      - NATS_SERVER=nats://nats-server:4222
  auth-ms:
    build:
      context: ./auth-ms
      args:
        - AUTH_MS_DATABASE_URL=${AUTH_MS_DATABASE_URL}
    image: auth-ms-prd
    environment:
      - PORT=3000
      - NATS_SERVER=nats://nats-server:4222
      - DATABASE_URL=${AUTH_MS_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
  products-ms:
    build: ./products-ms
    image: products-ms-prd
    environment:
      - PORT=3000
      - NATS_SERVER=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db
  orders-ms:
    build:
      context: ./orders-ms
      args:
        - ORDERS_MS_DATABASE_URL=${ORDERS_MS_DATABASE_URL}
    image: orders-ms-prd
    environment:
      - PORT=3000
      - NATS_SERVER=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_MS_DATABASE_URL}
  payments-ms:
    build: ./payments-ms
    image: payments-ms-prd
    ports:
      - 3003:3000
    environment:
      - PORT=3000
      - NATS_SERVER=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
